### ISSUE TITLE
default user proxy cannot be created/modified on Debian Buster because squid proxy is already running

### ISSUE THREAD

**Issue by nicenemo** [robertdebock/ansible-role-squid#2]
## Describe the bug

I have a standard net install of Debian 10. (Buster).
I try to get squid on it by using your role. I just mention the role and do nothing else.
Everything goes fine up to the point where it is trying to create the user. 
It cannot modify the existing proxy user because squid is already running.

## Playbook

```yaml
---
---
- name: Build proxy.
  hosts: proxy
  become: true
  vars_files:
  - 'environments/{{ environment_name }}/vars/environment.yml'
  roles:
  - ourbaselevelsystem.base
  - geerlingguy.security
  - innovalor.users
  - robertdebock.squid
  tasks:
  - name: Set apt proxy
    copy:
      content: 'Acquire::http::Proxy "{{ apt_proxy }}"; Acquire::https::Proxy "{{ apt_proxy }}";'
      dest: /etc/apt/apt.conf.d/01proxy
      mode: "0600"
    when: apt_proxy is defined
```

## Output

Show at least the error, possible related output, maybe just all the output.
```cmd
[..]
TASK [robertdebock.squid : include assert.yml] ***********************************************************************
included: /home/kruse/Projects/myproject/serverconfiguration/ansible/new_infrastructure/roles/robertdebock.squid/tasks/assert.yml for proxy1

TASK [robertdebock.squid : test if squid_port is set correctly] ******************************************************
ok: [proxy1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [robertdebock.squid : test if squid_cache_dir is set correctly] *************************************************
ok: [proxy1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [robertdebock.squid : test if squid_cache_dir is set correctly when no null driver is used] *********************
ok: [proxy1] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [robertdebock.squid : install squid] ****************************************************************************
ok: [proxy1]

TASK [robertdebock.squid : configure squid] **************************************************************************
ok: [proxy1]

TASK [robertdebock.squid : create group] *****************************************************************************
ok: [proxy1]

TASK [robertdebock.squid : create user] ******************************************************************************
fatal: [proxy1]: FAILED! => {"changed": false, "msg": "usermod: user proxy is currently used by process 4200\n", "name": "proxy", "rc": 8}

PLAY RECAP ***********************************************************************************************************
proxy1                     : ok=21   changed=0    unreachable=0    failed=1    skipped=5    rescued=0    ignored=0
```
## Environment

- Control node OS: Debian BullsEye on WSL 2.
- Control node Ansible version: 
```
ansible 2.9.12
[..,]
  python version = 3.8.5 (default, Aug  2 2020, 15:09:07) [GCC 10.2.0]
```
- Managed node OS:  Debian 10 Buster VM running in BHyve on SmartOS
