### ISSUE TITLE
Do not define default squid_cache_rules

### ISSUE THREAD

**Issue by meons** [robertdebock/ansible-role-squid#6]
## Describe the bug
If you override squid_acls only, the play will fail because of undefined ACLs in squid_cache_rules.

## Playbook

```yaml
---
- hosts: myhost
  become: true
  roles:
    - name: robertdebock.squid
      vars:
        squid_acls:
          - name: centosupdate
            classifier: dstdomain
            value: 'mirrorlist.centos.org'
        squid_http_access:
          - state: allow
            acls:
              - localhost
              - centos
```

## Output

`Processing: cache deny !Safe_ports\n2020/10/29 15:24:45| ACL not found: Safe_ports`

## Environment

- Control node OS: CentOS 8.2
- Control node Ansible version: 2.10.2

## Suggestion

Assertion `squid_cache_rules | length > 0` and default `squid_cache_rules` should be removed. For `squid_acls` and `squid_http_access` as well. The goal is to keep configuration simple.
